version: "3"
services:
  telegram-expense-bot:
    image: 'telegram-expense-bot:latest'
    restart: unless-stopped
    env_file:
      - .env.local
networks:
  default:
    name: nginx-proxy-manager
    external: true