on:
  pull_request:
  push:
    branches: [main, test-me-*]
jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on: ubuntu-latest
    env:
      IMG_CACHE: ghcr.io/aattwwss/telegram-expense-bot:${{ matrix.arch }}-latest
      IMG_VERSIONED: ghcr.io/aattwwss/telegram-expense-bot:${{ matrix.arch }}-${{ github.sha }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - run: docker run --rm --privileged tonistiigi/binfmt --install arm64
      if: matrix.arch == 'arm64'
    - name: build
      run: |
        set -euxo pipefail
        args=()
        if docker pull -q "$IMG_CACHE"; then
          args+=(--cache-from "$IMG_CACHE")
        fi
        docker buildx build \
            "${args[@]}" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --platform linux/${{ matrix.arch }} \
            --tag "$IMG_VERSIONED" \
            .
        docker tag "$IMG_VERSIONED" "$IMG_CACHE"
    - name: push
      run: |
        set -euxo pipefail
        docker login --username '${{ github.actor }}' --password '${{ secrets.GITHUB_TOKEN }}' ghcr.io
        docker push "$IMG_VERSIONED"
        docker push "$IMG_CACHE"
      if: github.event_name != 'pull_request'

  multiarch:
    if: github.event_name != 'pull_request'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - run: |
        set -euxo pipefail
        docker login --username '${{ github.actor }}' --password '${{ secrets.GITHUB_TOKEN }}' ghcr.io
        docker manifest create ghcr.io/aattwwss/telegram-expense-bot:latest \
          ghcr.io/aattwwss/telegram-expense-bot:arm64-latest \
          ghcr.io/aattwwss/telegram-expense-bot:amd64-latest
        docker manifest push ghcr.io/aattwwss/telegram-expense-bot:latest

